// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"miam-apiserver/internal/biz"
	"miam-apiserver/internal/conf"
	"miam-apiserver/internal/data"
	"miam-apiserver/internal/server"
	"miam-apiserver/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGormDB(confData, logger)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	policyRepo := data.NewPolicyRepo(dataData, logger)
	policyUsecase := biz.NewPolicyUsecase(policyRepo, logger)
	policyService := service.NewPolicyService(policyUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, confServer)
	userService := service.NewUserService(userUsecase)
	secretRepo := data.NewSecretRepo(dataData, logger)
	secretUsecase := biz.NewSecretUsecase(secretRepo, logger)
	secretService := service.NewSecretService(secretUsecase)
	grpcServer := server.NewGRPCServer(confServer, policyService, userService, secretService, logger)
	httpServer := server.NewHTTPServer(confServer, policyService, userService, secretService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
