// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.12.4
// source: secret/v1/secret.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSecretCreateSecret = "/secret.v1.Secret/CreateSecret"

type SecretHTTPServer interface {
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretReply, error)
}

func RegisterSecretHTTPServer(s *http.Server, srv SecretHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/secret", _Secret_CreateSecret0_HTTP_Handler(srv))
}

func _Secret_CreateSecret0_HTTP_Handler(srv SecretHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSecretRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSecretCreateSecret)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSecret(ctx, req.(*CreateSecretRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSecretReply)
		return ctx.Result(200, reply)
	}
}

type SecretHTTPClient interface {
	CreateSecret(ctx context.Context, req *CreateSecretRequest, opts ...http.CallOption) (rsp *CreateSecretReply, err error)
}

type SecretHTTPClientImpl struct {
	cc *http.Client
}

func NewSecretHTTPClient(client *http.Client) SecretHTTPClient {
	return &SecretHTTPClientImpl{client}
}

func (c *SecretHTTPClientImpl) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...http.CallOption) (*CreateSecretReply, error) {
	var out CreateSecretReply
	pattern := "/v1/secret"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSecretCreateSecret))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
